
import type { Metadata } from "next";
import { Inter, Roboto_Mono } from "next/font/google";


import "./globals.scss";
import ReduxProvider from "./components/ReduxProvider";
import { ThemeProvider } from "./context/ThemeContext";
import QueryProvider from "@/QueryProvider";
//import { useRef } from "react";


//const ref=useRef(null)

const geistSans = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const geistMono = Roboto_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        
        <ReduxProvider><ThemeProvider><QueryProvider>{children}</QueryProvider></ThemeProvider></ReduxProvider>
        
        
       
      </body>
    </html>
  );
}
